spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: yastest
    url: jdbc:mysql://192.168.0.188:3306/yastest?serverTimezone=GMT%2B8&useUnicode=true&useSSL=true #url
    username: root
    password: root
logging:
  level:
    com.springboot : debug
redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  jedis:
    pool:
      max-active: 1
      max-wait: -1
      max-idle: 10
      min-idle: 10
  timeout: 1000

mybatis-plus:
  mapper-locations: classpath*:com/springboot/**/mapping/*.xml
  type-aliases-package: com.springboot.**.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8899
# 日志文件存放位置
#log:
#  path: log
